INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Mensagem', 'Fernando Pessoa', 'Literatura', '1937');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('A Vida Que Vale a pena Ser Vivida', 'Clóvis de Barros Filho', 'Filosofia', '2010');
INSERT INTO TB_BOOK (NAME,AUTHOR, GENRE, YEAR) VALUES ('Em Busca de Nós Mesmos', 'Clóvis de Barros Filho', 'Filosofia', '2017');

